- name: 'Sending SMS Notification'
  uses: twilio-labs/actions-sms@v1-alpha
  with:
    fromPhoneNumber: '+1(832)5723014'
    toPhoneNumber: '+6593887784'
    message: 'Hello from Shanker'
  env:
    TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
    TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
    TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
runs:
  using: 'node12'
  main: 'dist/main.js'
